# Generated by Django 5.1.3 on 2024-11-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
